import Navbar from '@/components/navbar/Navbar';
import './globals.css';

export const metadata = {
  title: 'Amorae',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
